/**
 * Shared enums for NPC Empanelment & Contractual Engagement Portal.
 * These mirror the Prisma schema enums and are used across services.
 */

// ── User Roles ──────────────────────────────────────────
export enum UserRole {
  APPLICANT = 'APPLICANT',
  ADMIN = 'ADMIN',                          // Administration Group (GH Admin)
  SCREENING_MEMBER = 'SCREENING_MEMBER',    // Screening Committee
  EMPANELMENT_MEMBER = 'EMPANELMENT_MEMBER',// Empanelment Committee
  SELECTION_MEMBER = 'SELECTION_MEMBER',     // Selection Committee (contractual)
  DG = 'DG',                                // Director General
  IT_ADMIN = 'IT_ADMIN',
}

// ── Empanelment AI Section 2.3 — auto-classified category ──
export enum EmpanelmentCategory {
  ADVISOR = 'ADVISOR',
  SENIOR_CONSULTANT = 'SENIOR_CONSULTANT',
  CONSULTANT = 'CONSULTANT',
  PROJECT_ASSOCIATE = 'PROJECT_ASSOCIATE',
  YOUNG_PROFESSIONAL = 'YOUNG_PROFESSIONAL',
}

// ── AI-858/2026 Section A — engagement types ──
export enum EngagementType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  LUMP_SUM = 'LUMP_SUM',
  REVENUE_SHARE = 'REVENUE_SHARE',
  RESOURCE_PERSON = 'RESOURCE_PERSON',
}

// ── AI-858 Annex-II-A & II-B — contractual designations ──
export enum ContractualDesignation {
  SUPPORT_EXECUTIVE = 'SUPPORT_EXECUTIVE',
  OFFICE_EXECUTIVE = 'OFFICE_EXECUTIVE',
  ACCOUNTS_EXECUTIVE = 'ACCOUNTS_EXECUTIVE',
  TECHNICAL_EXECUTIVE = 'TECHNICAL_EXECUTIVE',
  LEGAL_EXECUTIVE = 'LEGAL_EXECUTIVE',
  PROJECT_EXECUTIVE = 'PROJECT_EXECUTIVE',
  RESEARCH_EXECUTIVE = 'RESEARCH_EXECUTIVE',
  SENIOR_PROFESSIONAL = 'SENIOR_PROFESSIONAL',
  YOUNG_PROFESSIONAL_CONTRACT = 'YOUNG_PROFESSIONAL_CONTRACT',
  CONSULTANT_CONTRACT = 'CONSULTANT_CONTRACT',
  SENIOR_CONSULTANT_CONTRACT = 'SENIOR_CONSULTANT_CONTRACT',
  ADVISOR_CONTRACT = 'ADVISOR_CONTRACT',
  SENIOR_ADVISOR = 'SENIOR_ADVISOR',
  EXPERT_RETIRED = 'EXPERT_RETIRED',
}

// ── Empanelment area — from existing NPC portal ──
export enum EmpanelmentArea {
  CONSULTANCY = 'CONSULTANCY',
  TRAINING = 'TRAINING',
  BOTH = 'BOTH',
}

// ── Application lifecycle statuses ──
export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  AUTO_SCREENED = 'AUTO_SCREENED',
  SCREENING_PENDING = 'SCREENING_PENDING',
  SCREENING_APPROVED = 'SCREENING_APPROVED',
  SCREENING_REJECTED = 'SCREENING_REJECTED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEW_COMPLETED = 'INTERVIEW_COMPLETED',
  COMMITTEE_EVALUATED = 'COMMITTEE_EVALUATED',
  RECOMMENDED = 'RECOMMENDED',
  NOT_RECOMMENDED = 'NOT_RECOMMENDED',
  DG_APPROVED = 'DG_APPROVED',
  DG_REJECTED = 'DG_REJECTED',
  LETTER_ISSUED = 'LETTER_ISSUED',
  ENGAGEMENT_ACTIVE = 'ENGAGEMENT_ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum AdvertStatus {
  DRAFT = 'DRAFT',
  DG_APPROVED = 'DG_APPROVED',
  PUBLISHED = 'PUBLISHED',
  CLOSED = 'CLOSED',
  SELECTION_DONE = 'SELECTION_DONE',
  CANCELLED = 'CANCELLED',
}

export enum ApplicantBackgroundType {
  GOVERNMENT_GROUP_A = 'GOVERNMENT_GROUP_A',
  GOVERNMENT_OTHER = 'GOVERNMENT_OTHER',
  CPSE = 'CPSE',
  AUTONOMOUS_BODY = 'AUTONOMOUS_BODY',
  PRIVATE_SECTOR = 'PRIVATE_SECTOR',
  ACADEMIC = 'ACADEMIC',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  FRESH_GRADUATE = 'FRESH_GRADUATE',
}

export enum MinQualification {
  CLASS_XII = 'CLASS_XII',
  ITI = 'ITI',
  GRADUATE = 'GRADUATE',
  LAW = 'LAW',
  POST_GRADUATE = 'POST_GRADUATE',
  PROFESSIONAL = 'PROFESSIONAL',
  DOCTORATE = 'DOCTORATE',
}
